version: "3.3"

services:
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - broker_adapter_network

  adapter:
    depends_on:
      - broker
      - influxdb
    build: ./adapter
    image: adapter
    env_file: env/adapter.env
    networks:
      - broker_adapter_network
      - adapter_influxdb_network

  influxdb:
    image: influxdb:1.8
    volumes:
      - ./influxdb/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - influxdb_data:/var/lib/influxdb
    networks:
      - adapter_influxdb_network
      - influxdb_grafana_network   
      
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    ports:
      - '80:3000'
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    env_file: env/grafana.env
    networks:
      - influxdb_grafana_network

networks:
  broker_adapter_network:
  adapter_influxdb_network:
  influxdb_grafana_network:

volumes:
  influxdb_data:
  grafana_data: